// <auto-generated />
namespace HackathonDashboard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Cascadeondeletesetfalse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cascadeondeletesetfalse));
        
        string IMigrationMetadata.Id
        {
            get { return "201601070602583_Cascade on delete set false"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
